### ISSUE TITLE
Never again kill a Promise

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/sphere-donut#11]
The code is forcing all potentially-asynchronous calls to the SPHERE.IO Platform to wait until the result is received (with `F.Promise.get()`), thus killing all advantages of the asynchronous computation that the SPHERE.IO client offers.

Let's take advantage of the nice Java 8 syntax and never kill a Promise again!

**Comment by yanns** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by emmenko** [comment]
It should be the title of a movie :movie_camera:

**Comment by lauraluiz** [comment]
I was tempted to use "break" instead of "kill" to put more drama on it :raised_hands:

**Comment by lauraluiz** [comment]
Depends on #9

**Comment by OlegIlyenko** [comment]
+1000 

"...  and never kill a Promise again!" such a beautiful ending!
